from typing import Dict, Any, List
from app.models import SummariseRunRequest, SummariseRunResponse
from app.config import SERVICE_ID

MANDATORY_DISCLAIMER = (
    "ASSISTIVE AI DRAFT: Generated by Abhisaran Assistive AI Service based strictly on "
    "verified deduction ledger records. This narrative has no authority over mathematical "
    "ACS calculations or institutional baseline scores."
)


def generate_run_narrative(req: SummariseRunRequest) -> SummariseRunResponse:
    score_str = f"{req.acs_score:.1f}" if req.acs_score is not None else "Not Calculable"
    band_name = req.alert_band.replace("_", " ") if req.alert_band else "Unclassified"

    lines = []
    lines.append(f"### Executive Diagnostic Summary for Facility `{req.facility_code}` (Run #{req.run_number})")
    lines.append("")

    # 1. Headline Assessment
    if req.is_provisional:
        lines.append(
            f"**Baseline Status:** PROVISIONAL. Facility `{req.facility_code}` attained a provisional "
            f"Abhisaran Continuity Score (ACS) of **{score_str} / 100.0** ({band_name} Alert Band). "
            f"Because assessed coverage reached {req.coverage_pct:.1f}% (below the 70.0% certification threshold), "
            f"this assessment serves as an interim baseline pending completion of unassessed sections."
        )
    else:
        lines.append(
            f"**Baseline Status:** CERTIFIED. Facility `{req.facility_code}` attained an official "
            f"Abhisaran Continuity Score (ACS) of **{score_str} / 100.0** ({band_name} Alert Band) with "
            f"{req.coverage_pct:.1f}% audit question coverage ({req.total_assessed_questions} of {req.total_applicable_questions} applicable questions verified)."
        )

    lines.append("")

    # 2. Key Loss Drivers
    key_findings = []
    priority_interventions = []

    sorted_ledger = sorted(req.ledger, key=lambda x: x.lost_weighted_points, reverse=True)

    if not sorted_ledger:
        lines.append("**Deduction Ledger Balance:** Full compliance recorded across all assessed indicators. Zero deductions registered.")
        key_findings.append("No compliance deductions recorded; all verified rubrics achieved full marks.")
    else:
        lines.append("**Primary Deduction Drivers:**")
        for idx, item in enumerate(sorted_ledger[:5], 1):
            finding_text = (
                f"[{item.question_id}] Page {item.page_number} ({item.severity} severity): "
                f"Lost {item.lost_weighted_points:.2f} weighted points ({item.deduction_percentage:.1f}% of total loss). "
                f"Finding: {item.loss_explanation}"
            )
            lines.append(f"{idx}. {finding_text}")
            key_findings.append(finding_text)

            if item.suggested_intervention and item.suggested_intervention not in priority_interventions:
                priority_interventions.append(f"[{item.question_id}] {item.suggested_intervention}")

    lines.append("")

    # 3. Red Flag Alerts
    if req.triggered_red_flags_count > 0:
        lines.append(
            f"⚠️ **Urgent Escalations:** {req.triggered_red_flags_count} critical red flag indicator(s) "
            f"were triggered during this evaluation. Immediate operational remediation is required to restore basic service viability."
        )
        lines.append("")

    # 4. Corrective Action Plan
    if priority_interventions:
        lines.append("**Recommended Prioritized Interventions:**")
        for idx, intervention in enumerate(priority_interventions[:5], 1):
            lines.append(f"- {intervention}")
        lines.append("")

    # 5. Non-ranking Notice
    lines.append(
        "> **Governance Policy:** In accordance with the non-ranking framework, this audit summary "
        "is intended solely for internal capacity development and resource targeting. "
        "It must not be utilized for inter-institutional league tables or competitive rankings."
    )

    narrative_text = "\n".join(lines)

    quality_metadata = {
        "ledger_items_analyzed": len(req.ledger),
        "total_points_loss_analyzed": sum(item.lost_weighted_points for item in req.ledger),
        "grounding_source": "DEDUCTION_LEDGER_SQL",
        "hallucination_index": 0.0,
        "is_provisional": req.is_provisional,
        "coverage_percentage": req.coverage_pct
    }

    return SummariseRunResponse(
        service_id=SERVICE_ID,
        summary_narrative=narrative_text,
        key_findings=key_findings,
        priority_interventions=priority_interventions,
        disclaimer=MANDATORY_DISCLAIMER,
        quality_metadata=quality_metadata
    )
